<?php
namespace app\modules\spot_set\models;

use app\common\base\BaseActiveRecord;

/**
 * This is the model class for table "{{%third_platform}}".
 *
 * @property integer $id
 * @property integer $spot_id
 * @property string  $platform_id
 * @property integer $spot_type_id
 * @property integer $create_time
 * @property integer $update_time
 */

class ThirdPlatform extends BaseActiveRecord{

    public static function tableName(){
        return '{{%third_platform}}';
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->spot_id=$this->spotId;

    }
    public function rules()
    {
        return [
            [['spot_id', 'platform_id','create_time', 'update_time','spot_type_id'], 'integer'],
        ];
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => '自增id',
            'spot_id' => '诊所id',
            'platform_id' => '允许开放预约平台ID',
            'spot_type_id'=>'服务类型ID',
            'create_time' => '创建时间',
            'update_time' => '更新时间',
        ];
    }
}